### PR TITLE
Expose task finished condition so that it can be created optimistically to avoid race on #wait.

### PR DESCRIPTION
**Pull request by ioquatix**
## Types of Changes

- [x] Bug fix.
- [x] New feature.
- [ ] Performance improvement.

## Testing

- [x] I added new tests for my changes.
- [x] I ran all the tests locally.

### CODE REVIEW

**Comment by igor-makarov** [comment]
@ioquatix that helps! The CocoaPods tests now don't output log noise.

However, don't you think this affects all tasks, and not just `Sync`?

**Comment by igor-makarov** [comment]
Example:
```
expect(Console.logger).not_to receive(:error)

task = Async do |task|
	task.async do 
		raise StandardError, "brain not provided"
	end.wait
end

expect do 
	task.wait
end.to raise_exception(StandardError, /brain/)
```

**Comment by ioquatix** [comment]
The logging does not affect behaviour.

**Comment by igor-makarov** [comment]
@ioquatix however, it does affect diagnostics in production - if errors are printed to production log as false positives, this will be bad for using the library.

Silencing errors in production isn't a good solution either.

**Comment by igor-makarov** [comment]
@ioquatix perhaps `@finished` should be always initialized in the initializer?

**Comment by ioquatix** [comment]
@igor-makarov if you do that, you end up silencing tasks that fails, and if no one calls wait, then the error is lost. Maybe it's okay, but in my experience, it causes developers to miss errors in their code.

**Comment by ioquatix** [comment]
Because the semantics of `Sync` should always be wait, I'm okay with this PR. But for the general case, I'm not sure it's good.

**Comment by jasl** [comment]
> @igor-makarov if you do that, you end up silencing tasks that fails, and if no one calls wait, then the error is lost. Maybe it's okay, but in my experience, it causes developers to miss errors in their code.

I think in CocoaPods, we finaly rescue all errors in main context, but the problem is when task raise error, the logger will first output it, the pass the error to main context.

Maybe redirect async's logger to file (or somewhere) is a better idea?

**Comment by igor-makarov** [comment]
I've added eager `@finished` init and ran all tests - nothing failed. Perhaps it's a good idea to move forward?

**Comment by jasl** [comment]
> I've added eager `@finished` init and ran all tests - nothing failed. Perhaps it's a good idea to move forward?

cool!

**Comment by igor-makarov** [comment]
@ioquatix let me see if I understand it correctly:

* Calling `#wait` on a task propagates the exception.
* Not calling `#wait` on a task at all is bad, as the exception will not be propagated. This is why the log print happens.
* If a task finishes before`#wait` is called, log print will occur because it doesn't know whether `#wait` get called.
* `#wait` can only be called if the task yields.

#### Therefore:
An exception raised in an unyielding task will get printed even if `#wait` is actually called.

**Comment by ioquatix** [comment]
> An exception raised in an unyielding task will get printed even if #wait is actually called.

Yes, but the key point is, if you handle it, even just by `rescue => error; error`, you won't get anything printed.

I don't feel that this is an unreasonable default, given the problems caused by missing errors.

The only case where I think doing this by default is when executing `Sync` which has the semantics of:

- If there is no reactor, create it and run it until completion or error, or
- If there is a reactor, run the code until completion or error.

The `Sync` semantics are designed for very high level entry points into code which is asynchronous but should look synchronous from the outside world no matter what (and efficiently). Actually the model for `Sync` is that it should be semantically the same as:

```
Async do
  # ...
end.wait
```

Whether an error is printed as a side effect is not specified, but I agree we could argue that it shouldn't because we always know `Sync` will call wait.

**Comment by bruno-** [comment]
What do you think about defaulting `finished` to `Async::Condition.new` in this case:

```ruby
task.async(finished: true) do
  # work
end.wait
```

**Comment by ioquatix** [comment]
I think the only valid use case is for `Sync`. I don't know if we should even document how that works (i.e. the option to `Task.new` should not be a public interface).

**Comment by ioquatix** [comment]
I thought about `finished: true` but I'm not sure there is a valid use case for it and it sits on the critical code path without any value in 99.99999999% of cases.

**Comment by ioquatix** [comment]
Okay, it's merged. `Sync` will never output exception to logger.

**Pull request merged**
