### PR TITLE
Update readme.md - fixing a typo

### PR DESCRIPTION
**Pull request by peychinov**
Just a typo fix.

### CODE REVIEW

**Comment by ioquatix** [comment]
Thanks!

To fix this properly, please fix the source document: https://github.com/socketry/async/tree/main/guides/getting-started

Then run:

```
bundle exec bake utopia:project:readme:update
```

Then submit both files in this PR. Thanks!

**Comment by olleolleolle** [comment]
@peychinov Perhaps, `group :maintenance, optional: true do` the gems that have these recipes, perhaps they're not included in your current installation?

So, to get those:

```
bundle config with maintenance
bundle
```

**Review by ioquatix — APPROVED** [review]
Thanks!

**Comment by ioquatix** [comment]
@olleolleolle is correct - in the past, I've had problems installing gems which I use for release management, documentation, and general maintenance in CI infrastructure, so I decided to split it out into an optional group. Sorry it caused confusion and thanks for giving it a go!

**Pull request merged**
